Replace &> /dev/null with >/dev/null 2>&1

diff --git a/arcade/arcade/templates/{{ toolkit_name }}/Makefile b/arcade/arcade/templates/{{ toolkit_name }}/Makefile
--- a/arcade/arcade/templates/{{ toolkit_name }}/Makefile
+++ b/arcade/arcade/templates/{{ toolkit_name }}/Makefile
@@ -7,9 +7,9 @@ help:
 .PHONY: install
 install: ## Install the poetry environment and install the pre-commit hooks
 	@echo "📦 Checking if Poetry is installed"
-	@if ! command -v poetry &> /dev/null; then \
-    	echo "📦 Poetry not found. Checking if pip is available"; \
-		if ! command -v pip &> /dev/null; then \
+	@if ! command -v poetry >/dev/null 2>&1; then \
+        echo "📦 Poetry not found. Checking if pip is available"; \
+		if ! command -v pip >/dev/null 2>&1; then \
 			echo "❌ pip is not installed. Please install pip first."; \
 			exit 1; \
 		fi; \
