fix tabs

diff --git a/.github/workflows/test-toolkits.yml b/.github/workflows/test-toolkits.yml
--- a/.github/workflows/test-toolkits.yml
+++ b/.github/workflows/test-toolkits.yml
@@ -54,7 +54,8 @@ jobs:
           uv run --active pre-commit run -a
           uv run --active mypy --config-file=pyproject.toml
 
-      - name: Test stand-alone toolkits (no secrets)
+      - name: Test stand-alone toolkits (with secrets)
+        if: github.repository == 'ArcadeAI/arcade-ai'
         working-directory: toolkits/${{ matrix.toolkit }}
         run: |
           # Run pytest and capture exit code
@@ -92,18 +93,16 @@ jobs:
           uv run --active mypy --config-file=pyproject.toml
 
       - name: Test stand-alone toolkits (no secrets)
-        if: github.repository == 'ArcadeAI/arcade-ai'
         working-directory: toolkits/${{ matrix.toolkit }}
         env:
           TEST_POSTGRES_DATABASE_CONNECTION_STRING: ${{ secrets.TEST_POSTGRES_DATABASE_CONNECTION_STRING }} # TODO: dynamically only load the `TEST_${{ matrix.toolkit }}_DATABASE_CONNECTION_STRING secret`
         run: |
-          if:
-            # Run pytest and capture exit code
-            uv run --active pytest -W ignore -v --cov=arcade_${{ matrix.toolkit }} --cov-report=xml || EXIT_CODE=$?
+          # Run pytest and capture exit code
+          uv run --active pytest -W ignore -v --cov=arcade_${{ matrix.toolkit }} --cov-report=xml || EXIT_CODE=$?
 
-            if [ "${EXIT_CODE:-0}" -eq 5 ]; then
-              echo "No tests found for toolkit ${{ matrix.toolkit }}, skipping..."
-              exit 0
-            elif [ "${EXIT_CODE:-0}" -ne 0 ]; then
-              exit ${EXIT_CODE}
+          if [ "${EXIT_CODE:-0}" -eq 5 ]; then
+            echo "No tests found for toolkit ${{ matrix.toolkit }}, skipping..."
+            exit 0
+          elif [ "${EXIT_CODE:-0}" -ne 0 ]; then
+            exit ${EXIT_CODE}
           fi
